### ISSUE TITLE
zero vram

### ISSUE THREAD

**Issue by laughingFish** [diddlesnaps/gog-galaxy-wine#1]
Have tested three games: No Man's Sky, Titan Quest, Far Cry.  All fail to run.  Wine reports insufficient vram found.  System is intel 8400 cpu with 16GB RAM, 6GB nVidia 1060 using latest proprietary driver in Kubuntu 18:04.  The games cannot initialize an opengl window.

rmkelsey@zoho.com

**Comment by lucyllewy** [comment]
Can you try closing GOG Galaxy, running the following in a terminal, and then attempt the games again:

```bash
sudo snap connect gog-galaxy-wine:hardware-observe
```

This might allow the appropriate permissions for the games to detect the amount of VRAM on the system.

**Comment by laughingFish** [comment]
Issue was resolved with nVidia driver 396.45.
Thanks!
