### ISSUE TITLE
Wine games files

### ISSUE THREAD

**Issue by miseym** [diddlesnaps/gog-galaxy-wine#13]
I'm trying to install mods for the Planescape: Torment (wide-screen etc) which need to be run in the game folder, but I can't find the game files. What's the default location?

**Comment by lucyllewy** [comment]
All the files for GOG Galaxy are stored in `~/snap/gog-galaxy-wine/common` with the `C:` equivalent being rooted at `~/snap/gog-galaxy-wine/common/.wine/drive_c`.

**Comment by miseym** [comment]
Brilliant, much appreciated.
