### ISSUE TITLE
Update SNAP description

### ISSUE THREAD

**Issue by DmitriiNesterovMHE** [diddlesnaps/gog-galaxy-wine#15]
At https://snapcraft.io/gog-galaxy-wine description there is a link to audacity project instead of this one. Please update.
![Screenshot_20190924_195043](https://user-images.githubusercontent.com/20519495/65532535-a6a1de00-df04-11e9-9714-a3f72d870476.png)

**Comment by lucyllewy** [comment]
oops. Thanks for spotting that :-)

**Comment by lucyllewy** [comment]
fixed :-) thankyou again!
