### ISSUE TITLE
Installation creates iTunes desktop link

### ISSUE THREAD

**Issue by fubar-coder** [diddlesnaps/gog-galaxy-wine#27]
How to reproduce:

1. Use Ubuntu 21.10
2. Start "Ubuntu Software"
3. Install `gog-galaxy-wine`

The "start menu" now contains the iTunes link.

`locate iTunes` produces:

```text
/snap/gog-galaxy-wine/499/meta/gui/itunes.desktop
/var/lib/snapd/desktop/applications/gog-galaxy-wine_itunes.desktop
```

My question now is: Why is there an "iTunes" desktop file?

**Comment by TomSnout** [comment]
Likewise, I'm experiencing the same issue using pop-os 21.04.

I was following the instructions on this video: https://youtu.be/stmt7tVm6Uo

**Comment by lucyllewy** [comment]
This is weird. The git changelog shows that I added it in September, but I have no idea why I did that. It shouldn't be there, as you rightly point out. I've removed it, and the client is rebuilding now. It'll be available shortly.
